// auto-generated icon type definitions from /icons-build-type-definitions.js
declare type Icons =
  | "angle-right-regular"
  | "angle-left-regular"
  | "angle-down-regular"
  | "angle-up-regular"
  | "chevron-right-regular"
  | "truck-fast-regular"
  | "plus-regular"
  | "xmark-regular"
  | "circle-info-regular"
  | "circle-xmark-regular"
  | "folder-closed-regular"
  | "folder-open-regular"
  | "magnifying-glass-regular"
  | "input-text-regular"
  | "caret-down-solid"
  | "angle-right-solid"
  | "circle-check-solid"
  | "folder-open-sharp-regular"
  | "folder-closed-sharp-regular";
